const attendenceListData = [
    {
        id: 1,
        student_name: "Sophie Lambert",
        student_id: "ACT1420",
        date: "9/13/2025",
        status: "present",
        attendence_by: "manual",
    },
    {
        id: 2,
        student_name: "Liam Johnson",
        student_id: "ACT1421",
        date: "9/13/2025",
        status: "absent",
        attendence_by: "manual",
    },
    {
        id: 3,
        student_name: "Ava Martinez",
        student_id: "ACT1422",
        date: "9/13/2025",
        status: "present",
        attendence_by: "scanner",
    },
    {
        id: 4,
        student_name: "Noah Wilson",
        student_id: "ACT1423",
        date: "9/13/2025",
        status: "late",
        attendence_by: "manual",
    },
    {
        id: 5,
        student_name: "Emma Brown",
        student_id: "ACT1424",
        date: "9/13/2025",
        status: "present",
        attendence_by: "scanner",
    },
    {
        id: 6,
        student_name: "James Davis",
        student_id: "ACT1425",
        date: "9/13/2025",
        status: "present",
        attendence_by: "manual",
    },
    {
        id: 7,
        student_name: "Olivia Garcia",
        student_id: "ACT1426",
        date: "9/13/2025",
        status: "absent",
        attendence_by: "scanner",
    },
    {
        id: 8,
        student_name: "Benjamin Miller",
        student_id: "ACT1427",
        date: "9/13/2025",
        status: "present",
        attendence_by: "manual",
    },
    {
        id: 9,
        student_name: "Isabella Anderson",
        student_id: "ACT1428",
        date: "9/13/2025",
        status: "late",
        attendence_by: "manual",
    },
    {
        id: 10,
        student_name: "William Thomas",
        student_id: "ACT1429",
        date: "9/13/2025",
        status: "present",
        attendence_by: "scanner",
    },
    {
        id: 11,
        student_name: "Mia Taylor",
        student_id: "ACT1430",
        date: "9/13/2025",
        status: "present",
        attendence_by: "manual",
    },
    {
        id: 12,
        student_name: "Lucas Moore",
        student_id: "ACT1431",
        date: "9/13/2025",
        status: "absent",
        attendence_by: "scanner",
    },
    {
        id: 13,
        student_name: "Charlotte Jackson",
        student_id: "ACT1432",
        date: "9/13/2025",
        status: "present",
        attendence_by: "manual",
    },
    {
        id: 14,
        student_name: "Henry White",
        student_id: "ACT1433",
        date: "9/13/2025",
        status: "late",
        attendence_by: "scanner",
    },
    {
        id: 15,
        student_name: "Amelia Harris",
        student_id: "ACT1434",
        date: "9/13/2025",
        status: "present",
        attendence_by: "manual",
    },
];

export default attendenceListData;