export const eventsData = [
  {
    id: 1,
    event_name: "Annual Alumni Meetup",
    schedule: "12 July, Monday • 1:30 PM",
    location: "Main Theater",
    amount: "$246",
    status: "completed",
    description: "Join us for an evening of outstanding performances by our talented students.",
  },
  {
    id: 2,
    event_name: "Science Fair Showcase",
    schedule: "18 July, Sunday • 11:00 AM",
    location: "Auditorium Hall",
    amount: "$180",
    status: "completed",
    description: "Students present science projects and live experiments to families and guests.",
  },
  {
    id: 3,
    event_name: "Parent Engagement Session",
    schedule: "24 July, Saturday • 3:15 PM",
    location: "Conference Room A",
    amount: "$95",
    status: "completed",
    description: "A collaborative session focused on student growth, progress updates, and planning.",
  },
  {
    id: 4,
    event_name: "Career Development Workshop",
    schedule: "05 August, Thursday • 10:30 AM",
    location: "Innovation Lab",
    amount: "$210",
    status: "upcoming",
    description: "Industry mentors will guide students through career planning and interview preparation.",
  },
  {
    id: 5,
    event_name: "Cultural Celebration Day",
    schedule: "11 August, Wednesday • 2:00 PM",
    location: "Campus Courtyard",
    amount: "$320",
    status: "upcoming",
    description: "A vibrant celebration featuring student performances, food, and cultural exhibitions.",
  },
  {
    id: 6,
    event_name: "Winter Scholarship Briefing",
    schedule: "19 August, Friday • 12:45 PM",
    location: "Seminar Room 2",
    amount: "$150",
    status: "upcoming",
    description: "An information session covering scholarship opportunities, deadlines, and application tips.",
  },
];
