export const transactionsData = [
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10001",
    user_name: "Sophie Lambert",
    payment_type: "Card",
    payment_plan: "Monthly Installment",
    amount: 250,
    date: "2025-09-01",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10002",
    user_name: "Jerome Bell",
    payment_type: "PayPal",
    payment_plan: "One-Time",
    amount: 120,
    date: "2025-09-02",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10003",
    user_name: "Kristin Watson",
    payment_type: "Card",
    payment_plan: "Yearly",
    amount: 900,
    date: "2025-09-02",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10004",
    user_name: "Ronald Richards",
    payment_type: "Stripe",
    payment_plan: "Monthly Installment",
    amount: 180,
    date: "2025-09-03",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10005",
    user_name: "Wade Warren",
    payment_type: "Card",
    payment_plan: "One-Time",
    amount: 320,
    date: "2025-09-03",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10006",
    user_name: "Eleanor Pena",
    payment_type: "PayPal",
    payment_plan: "Yearly",
    amount: 1100,
    date: "2025-09-04",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10007",
    user_name: "Floyd Miles",
    payment_type: "Card",
    payment_plan: "Monthly Installment",
    amount: 200,
    date: "2025-09-04",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10008",
    user_name: "Devon Lane",
    payment_type: "Stripe",
    payment_plan: "Monthly Installment",
    amount: 175,
    date: "2025-09-05",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10009",
    user_name: "Ralph Edwards",
    payment_type: "Card",
    payment_plan: "One-Time",
    amount: 400,
    date: "2025-09-05",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10010",
    user_name: "Bessie Cooper",
    payment_type: "PayPal",
    payment_plan: "Yearly",
    amount: 980,
    date: "2025-09-06",
  },

  {
    user_id: "USR-1008",
    transaction_id: "TXN-10011",
    user_name: "Guy Hawkins",
    payment_type: "Card",
    payment_plan: "Monthly Installment",
    amount: 210,
    date: "2025-09-06",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10012",
    user_name: "Jenny Wilson",
    payment_type: "Stripe",
    payment_plan: "One-Time",
    amount: 150,
    date: "2025-09-07",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10013",
    user_name: "Darlene Robertson",
    payment_type: "Card",
    payment_plan: "Monthly Installment",
    amount: 230,
    date: "2025-09-07",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10014",
    user_name: "Jacob Jones",
    payment_type: "PayPal",
    payment_plan: "Yearly",
    amount: 1050,
    date: "2025-09-08",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10015",
    user_name: "Kathryn Murphy",
    payment_type: "Card",
    payment_plan: "One-Time",
    amount: 275,
    date: "2025-09-08",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10016",
    user_name: "Leslie Alexander",
    payment_type: "Stripe",
    payment_plan: "Monthly Installment",
    amount: 190,
    date: "2025-09-09",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10017",
    user_name: "Cody Fisher",
    payment_type: "Card",
    payment_plan: "Monthly Installment",
    amount: 220,
    date: "2025-09-09",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10018",
    user_name: "Savannah Nguyen",
    payment_type: "PayPal",
    payment_plan: "Yearly",
    amount: 1200,
    date: "2025-09-10",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10019",
    user_name: "Courtney Henry",
    payment_type: "Card",
    payment_plan: "One-Time",
    amount: 310,
    date: "2025-09-10",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10020",
    user_name: "Annette Black",
    payment_type: "Stripe",
    payment_plan: "Monthly Installment",
    amount: 205,
    date: "2025-09-11",
  },

  {
    user_id: "USR-1008",
    transaction_id: "TXN-10021",
    user_name: "Theresa Webb",
    payment_type: "Card",
    payment_plan: "Monthly Installment",
    amount: 215,
    date: "2025-09-11",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10022",
    user_name: "Brooklyn Simmons",
    payment_type: "PayPal",
    payment_plan: "Yearly",
    amount: 990,
    date: "2025-09-12",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10023",
    user_name: "Eleanor Pena",
    payment_type: "Card",
    payment_plan: "One-Time",
    amount: 260,
    date: "2025-09-12",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10024",
    user_name: "Ralph Edwards",
    payment_type: "Stripe",
    payment_plan: "Monthly Installment",
    amount: 195,
    date: "2025-09-13",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10025",
    user_name: "Kristin Watson",
    payment_type: "Card",
    payment_plan: "Monthly Installment",
    amount: 240,
    date: "2025-09-13",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10026",
    user_name: "Devon Lane",
    payment_type: "PayPal",
    payment_plan: "Yearly",
    amount: 1150,
    date: "2025-09-14",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10027",
    user_name: "Floyd Miles",
    payment_type: "Card",
    payment_plan: "One-Time",
    amount: 340,
    date: "2025-09-14",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10028",
    user_name: "Jerome Bell",
    payment_type: "Stripe",
    payment_plan: "Monthly Installment",
    amount: 185,
    date: "2025-09-15",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10029",
    user_name: "Bessie Cooper",
    payment_type: "Card",
    payment_plan: "Yearly",
    amount: 1020,
    date: "2025-09-15",
  },
  {
    user_id: "USR-1008",
    transaction_id: "TXN-10030",
    user_name: "Wade Warren",
    payment_type: "PayPal",
    payment_plan: "One-Time",
    amount: 290,
    date: "2025-09-16",
  },
];
